site_name: endiku's Cookbook
theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:

    # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 


    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

    # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode


  markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

  nav:
  - Machines:
    - section/index.md
    - HTB Test: section/page-1.md
  
  - Cheatsheets:
    - section/index.md
    - Linux: section/page-1.md